require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'

target 'TestProject' do
  use_frameworks! :linkage => :static
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  target 'TestProjectTests' do
    inherit! :complete
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => false
  )
end
